server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://118.89.192.65:3306/innkp?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: innkp
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 118.89.192.65
    port: 6379
    password: innkp
    database: 0
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1